#!/usr/bin/env bash
# MOSS-Realtime demo — the ONE deploy entrypoint (Procfile/overmind pattern,
# hand-rolled on tmux because this box is air-gapped): every process is a
# named window in a single tmux session, so the stack comes up with one
# command, each process is attachable, and one can be restarted without
# touching the others.
#
#   demo.sh up [KEY=VALUE …]  bring the whole demo up (kills any previous run)
#   demo.sh down             tear everything down (incl. legacy session names,
#                            orphaned workers/sidecars, and this repo's stray
#                            gateways/vite that escaped tmux)
#   demo.sh restart api|web  respawn ONE process, leave the other alone
#   demo.sh status           sessions + health in one glance
#   demo.sh doctor           who is REALLY serving? port listeners, strays,
#                            tunnels, boot-stamp identity (compare against
#                            <browser-link>/api/health — pod-pinned proxy
#                            links routinely point at a STALE pod's stack)
#   demo.sh logs [api|web|build|backend|workers|tts|sglang]   follow the logs (logs/ in-repo)
#   demo.sh attach           tmux attach (Ctrl-B D detaches, Ctrl-B 0/1 switch)
#
# Processes (the whole manifest — the backend owns its TTS sidecar itself,
# spawn/health-gate/terminate in server lifespan, so there is NO sidecar step):
#   api  run_backend.sh   uvicorn on :8000, autoloads the VLM checkpoint
#   web  run_web.sh       vite build --watch + vite preview on :20941
#
# Config layers (server/config.py docstring): command line > startup-script
# pins > .env.deploy > config.py defaults. "Command line" here is the env
# prefix (`MODEL_PATH=x demo.sh up`) or trailing KEY=VALUE args (`demo.sh up
# MODEL_PATH=x` — the args win over the prefix; both are forwarded INTO the
# tmux windows, which otherwise read the tmux server's env). Also useful:
# DEMO_SKIP_GPU=1 (CPU/dev box), API_WAIT_S (default 1800 — the backend
# health-gates TTS sidecars + VLM workers + ASR in lifespan BEFORE uvicorn
# answers: ~10 min warm, 15-20 min on a cold shared-FS pod; expiry with a
# LIVE api window warns and continues — only the window dying is fatal)
# and VLM_WAIT_S (default 480).
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# ---- command line (config layer 1): subcommand + KEY=VALUE overrides ----
CMD="" ; POS=() ; ARG_KEYS=()
for arg in "$@"; do
  case "$arg" in
    [A-Za-z_]*=*)
      key="${arg%%=*}"
      case "$key" in
        *[!A-Za-z0-9_]*) POS+=("$arg") ;;
        *) export "$key=${arg#*=}"; ARG_KEYS+=("$key") ;;
      esac ;;
    *) if [ -z "$CMD" ]; then CMD="$arg"; else POS+=("$arg"); fi ;;
  esac
done
CMD="${CMD:-up}"

# ---- .env.deploy (config layer 3; box-local, gitignored) ----
# loaded AFTER the command line so caller env + KEY=VALUE args win; keys seen
# in the file are recorded so fwd_env can carry them into the tmux windows.
. "$REPO/scripts/deploy/env_lib.sh"
load_env_deploy "$REPO"
SES="${DEMO_SESSION:-moss}"
API_PORT="${PORT:-8000}"
WEB_PORT="${WEB_PORT:-20941}"
# in-repo log tree (gitignored; shared FS → survives pod restarts, readable
# from the CPU box) — exactly TWO subtrees:
#   handler/  code-owned rotating python logs (backend, workers, tts engines;
#             paths come from MOSS_LOG_FILE / VLM_WORKER_LOG_DIR /
#             TTS_SIDECAR_LOG defaults in run_backend.sh + config.py — NOT
#             from LOG_ROOT, same asymmetry as before)
#   stdout/   raw window captures (api/web console, vite build), rotated for
#             real by scripts/deploy/rotating_tee.py
LOG_ROOT="${LOG_ROOT:-$REPO/logs}"
# rotating_tee interpreter: the backend venv's python, else any python3
PYBIN="${PYBIN:-$REPO/.venv/bin/python}"
[ -x "$PYBIN" ] || PYBIN="$(command -v python3 || echo python3)"
# a FUNCTION, not a "$CURL" command string: unquoted expansion would glob
# the bare * (--noproxy) against whatever the current directory holds
CURL() { curl --noproxy '*' -sf --max-time 3 "$@"; }
# Every settings var the python/shell layers consume — GENERATED by
# scripts/dev/check_env.py from server/config.py + the direct-env readers
# (run `check_env.py --write` after adding a setting; `--check` lints drift).
. "$REPO/scripts/deploy/env_manifest.sh"
# What crosses the tmux boundary: the full manifest, plus whatever .env.deploy
# provided (so even a stale manifest can't drop a file-provided var), plus the
# command-line KEY=VALUE names. fwd_env skips unset/empty; dups are harmless.
FWD_VARS=("${MOSS_ENV_VARS[@]}" "${ENV_DEPLOY_KEYS[@]}" "${ARG_KEYS[@]}")

# caller env → window env, safely quoted (printf %q)
fwd_env() {
  local v out=""
  for v in "${FWD_VARS[@]}"; do
    [ -n "${!v:-}" ] && out+="$(printf '%s=%q ' "$v" "${!v}")"
  done
  printf '%s' "$out"
}

win_cmd() { # $1 window name, $2 script
  # rotating_tee replaces `tee -a`: real 32 MiB × 5 rotation, still echoes to
  # the tmux pane (no --quiet), and outlives a respawn-kill until stdin EOF
  printf 'env %sMOSS_DEPLOY_REPO=%q MOSS_DEPLOY_ROLE=demo bash %q 2>&1 | %q %q %q' \
    "$(fwd_env)" "$REPO" "$REPO/scripts/deploy/$2" \
    "$PYBIN" "$REPO/scripts/deploy/rotating_tee.py" "$LOG_ROOT/stdout/$1/console.log"
}

prep_logs() {
  # stdout/ capture dirs (the tee mkdirs too — this keeps first-boot obvious);
  # handler/ dirs are created by the python processes themselves
  mkdir -p "$LOG_ROOT/stdout/api" "$LOG_ROOT/stdout/web"
}

gpu_preflight() {
  [ -n "${DEMO_SKIP_GPU:-}" ] && { echo "[preflight] skipped (DEMO_SKIP_GPU)"; return; }
  # Accept either nvidia-smi (GPU) or npu-smi (Ascend NPU)
  if command -v npu-smi >/dev/null 2>&1; then
    echo "[preflight] NPU detected (npu-smi) — skipping nvidia-smi check."
    return
  fi
  if ! command -v nvidia-smi >/dev/null; then
    echo "No nvidia-smi or npu-smi on this box — no accelerator here. Run on the"
    echo "GPU/NPU box, or DEMO_SKIP_GPU=1 for a frontend/CPU-only bring-up."
    exit 1
  fi
  echo "[preflight] GPU driver sanity (nvidia-smi, 10s budget) ..."
  # plain `timeout nvidia-smi` is a trap: a wedged driver leaves it in
  # unkillable D-state and timeout waits forever — poll a backgrounded probe
  nvidia-smi --query-gpu=name --format=csv,noheader >/dev/null 2>&1 &
  local pid=$! st ok=""
  for _ in $(seq 1 10); do
    st="$(ps -o stat= -p "$pid" 2>/dev/null || true)"
    case "$st" in ""|Z*) ok=1; break ;; esac
    sleep 1
  done
  if [ -z "$ok" ]; then
    disown "$pid" 2>/dev/null || true
    echo "GPU wedged (nvidia-smi stuck in D-state) — the pod needs a platform"
    echo "restart first. Not touching any running sessions."
    exit 1
  fi
  wait "$pid" || { echo "nvidia-smi errored — GPU not usable; aborting."; exit 1; }
}

# PIDs of THIS checkout's serving processes that escaped tmux — nohup'd vite
# previews (publish runbooks), HUP-orphaned gateways on non-default ports.
# Scoped by /proc/<pid>/cwd == this repo: the gateway's argv is relative
# (".venv/bin/python -m uvicorn …"), so cwd is the only reliable ownership
# test, and it guarantees another checkout's stack is never touched.
stray_pids() {
  local pid cwd
  for pid in $(pgrep -f 'uvicorn server\.app:app|node_modules/(\.bin/)?vite|vite/bin/vite\.js' 2>/dev/null); do
    [ "$pid" = "$$" ] && continue
    cwd="$(readlink "/proc/$pid/cwd" 2>/dev/null || true)"
    case "$cwd" in "$REPO"|"$REPO"/*) echo "$pid" ;; esac
  done
}

# Tunnel/relay clients publish SOME stack to the user's browser — never killed
# here (they may belong to another deployment on purpose), but always shown:
# a relay pointed at a dead/stale port is exactly how "restarted but no good"
# happens (browser traffic lands on an instance demo.sh does not manage).
warn_tunnels() {
  local tun
  tun="$(pgrep -af 'cloudflared|frpc|rtunnel|fkqz|phddns' 2>/dev/null || true)"
  if [ -n "$tun" ]; then
    echo "NOTE: tunnel/relay clients running (NOT killed — check what they publish):"
    echo "$tun" | sed 's/^/   /'
  fi
}

down() {
  # Request graceful API shutdown before tmux delivers SIGHUP. After the
  # bounded TERM/KILL sequence, continue startup even if exit is unconfirmed.
  "$PYBIN" "$REPO/scripts/deploy/stop_backend.py" --repo "$REPO" || return 1
  # A session name alone is not ownership. Leave unmarked/foreign sessions.
  local s
  for s in "$SES" moss_tts moss_api moss_web moss_build; do
    [ "$(tmux show-option -v -t "$s" @moss_repo 2>/dev/null || true)" = "$REPO" ] || continue
    tmux kill-session -t "$s" 2>/dev/null && echo "killed tmux session: $s" || true
  done
  "$PYBIN" "$REPO/scripts/deploy/stop_backend.py" --repo "$REPO" --role demo || return 1
  echo "Unmarked legacy sidecars/sessions are not stopped automatically; inspect with doctor."
  warn_tunnels
}

up() {
  gpu_preflight
  down
  if tmux has-session -t "$SES" 2>/dev/null; then
    echo "FATAL: tmux session $SES is not owned by this checkout; set DEMO_SESSION to an unused name." >&2
    return 1
  fi
  prep_logs
  # vLLM-Omni's MOSS codec loader needs the conditional-Identity projection fix
  # or MOSS-TTS-Realtime dies at weight load (missing=6). Idempotent, and a pip
  # (re)install of vllm-omni silently reverts it — so re-assert on every up.
  if [ -x "$REPO/.venv-vllm/bin/python" ]; then
    "$REPO/.venv-vllm/bin/python" "$REPO/scripts/patch_vllm_omni_moss_codec.py" || true
  fi
  tmux new-session  -d -s "$SES" -n api "$(win_cmd api run_backend.sh)"
  tmux set-option -t "$SES" @moss_repo "$REPO"
  tmux new-window   -t "$SES" -n web "$(win_cmd web run_web.sh)"
  echo "[1/3] api starting on :$API_PORT (backend spawns+gates its own TTS sidecar)"

  # uvicorn only answers AFTER lifespan finishes gating every TTS sidecar,
  # VLM worker and the ASR load — ~10 min on a warm box, 15-20 min on a cold
  # shared-FS pod (venv imports + weights all cross the network FS), so this
  # first gate needs its own long budget (VLM_WAIT_S covers [2/3]). Budget
  # expiry with a LIVE api window is a slow boot, not a failure: warn and
  # fall through to [2/3], which keeps polling (2026-08-07: a 1017 s cold
  # boot vs the then-600 s budget made a healthy startup look dead). Only
  # the api WINDOW closing is fatal — it is the real death signal (the
  # session outlives it via the web window, so has-session alone would
  # stall the full wait).
  local status="" waited=0 budget="${API_WAIT_S:-1800}"
  while [ "$waited" -lt "$budget" ]; do
    status=$(CURL "http://127.0.0.1:$API_PORT/api/status" || true)
    [ -n "$status" ] && break
    tmux list-windows -t "$SES" -F '#W' 2>/dev/null | grep -qx api \
      || { echo "api died at boot — see $LOG_ROOT/stdout/api/console.log"; exit 1; }
    sleep 2; waited=$(( waited + 2 ))
    # long silent waits read as a hang — heartbeat every 2 min
    [ $(( waited % 120 )) -eq 0 ] \
      && echo "      ... still booting (${waited}s, api window alive) — $LOG_ROOT/stdout/api/console.log"
  done
  if [ -n "$status" ]; then
    echo "      api: up (${waited}s)"
  else
    echo "      WARNING: api not answering after ${budget}s but the window is alive —"
    echo "      likely a slow cold-FS boot; continuing (watch $LOG_ROOT/stdout/api/console.log)."
  fi

  echo "[2/3] waiting for the VLM checkpoint (up to ${VLM_WAIT_S:-480}s) ..."
  local loaded=""
  for i in $(seq 1 $(( ${VLM_WAIT_S:-480} / 4 ))); do
    status=$(CURL "http://127.0.0.1:$API_PORT/api/status" || true)
    printf '%s' "$status" | grep -q '"loaded":true' && { loaded=1; break; }
    sleep 4
  done
  if [ -n "$loaded" ]; then
    echo "      vlm: loaded"
  else
    echo "      WARNING: VLM not loaded — realtime sessions will refuse until it is."
    echo "      (fine on a CPU box; otherwise check $LOG_ROOT/handler/backend/backend.log, or load by hand:"
    echo "       curl -X POST http://127.0.0.1:$API_PORT/api/models/load -H 'content-type: application/json' \\"
    echo "            -d '{\"model_path\":\"...\",\"gpu_id\":0,\"hf_mode\":\"online_streaming\"}')"
  fi

  echo "[3/3] web (preview + build-on-save watcher) on :$WEB_PORT"
  sleep 3
  CURL "http://127.0.0.1:$WEB_PORT/" >/dev/null && echo "      web: up" \
    || echo "      web not answering yet — $LOG_ROOT/stdout/web/console.log"
  echo "UP — web :$WEB_PORT · api :$API_PORT · logs $LOG_ROOT/{handler,stdout} · '$0 status' any time"
}

restart_one() { # $1 = api|web
  local w="$1"
  case "$w" in api|web) ;; *) echo "restart what? api|web"; exit 2 ;; esac
  tmux has-session -t "$SES" 2>/dev/null || { echo "stack is down — use '$0 up'"; exit 1; }
  [ "$(tmux show-option -v -t "$SES" @moss_repo 2>/dev/null || true)" = "$REPO" ] \
    || { echo "FATAL: tmux session $SES is unmarked or belongs to another checkout" >&2; return 1; }
  if [ "$w" = api ]; then
    "$PYBIN" "$REPO/scripts/deploy/stop_backend.py" --repo "$REPO" --port "$API_PORT" || return 1
  fi
  if tmux list-windows -t "$SES" -F '#W' 2>/dev/null | grep -qx "$w"; then
    tmux respawn-window -k -t "$SES:$w" "$(win_cmd "$w" "run_${w/api/backend}.sh")"
  else
    # Graceful exit can remove the last window and its tmux session.
    if tmux has-session -t "$SES" 2>/dev/null; then
      tmux new-window -t "$SES" -n "$w" "$(win_cmd "$w" "run_${w/api/backend}.sh")"
    else
      tmux new-session -d -s "$SES" -n "$w" "$(win_cmd "$w" "run_${w/api/backend}.sh")"
      tmux set-option -t "$SES" @moss_repo "$REPO"
    fi
  fi
  echo "respawned: $w (log $LOG_ROOT/stdout/$w/console.log)"
}

status() {
  echo "-- tmux:"
  tmux list-windows -t "$SES" -F '   #S:#W (#{pane_current_command})' 2>/dev/null \
    || echo "   session '$SES' not running"
  echo "-- api :$API_PORT:"
  CURL "http://127.0.0.1:$API_PORT/api/status" 2>/dev/null \
    | grep -o '"loaded":[a-z]*\|"model_path":"[^"]*"\|"active_sessions":[0-9]*' \
    | sed 's/^/   /' || echo "   not answering"
  echo "-- web :$WEB_PORT:"
  CURL -o /dev/null "http://127.0.0.1:$WEB_PORT/" 2>/dev/null \
    && echo "   200 (serving dist/)" || echo "   not answering"
}

# Which stack does the user's BROWSER actually reach? demo.sh only manages
# THIS pod's tmux session — notebook-gateway /proxy/<port>/ links are pinned
# to the pod that minted them, and tunnels publish whatever they were started
# against. `doctor` surfaces everything that could be serving instead of us.
doctor() {
  echo "pod: $(hostname)   repo: $REPO   tmux session: $SES"
  echo "-- listeners on demo ports (api/web/workers/tts + publish-doc ports 4173/5173):"
  ss -ltnp 2>/dev/null \
    | grep -E ":($API_PORT|$WEB_PORT|4173|5173|900[0-7]|1810[0-7]|3080[0-7])\s" \
    | sed 's/^/   /' || echo "   (none)"
  echo "-- this repo's serving processes outside tmux (strays; 'down' kills these):"
  local pid found=""
  for pid in $(stray_pids); do
    found=1
    printf '   pid %s  %s\n' "$pid" "$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null | cut -c1-120)"
  done
  [ -n "$found" ] || echo "   (none)"
  warn_tunnels
  echo "-- identity: THIS stack's gateway boot stamp:"
  CURL "http://127.0.0.1:$API_PORT/api/health" 2>/dev/null | sed 's/^/   /' || echo "   not answering"
  echo "   → open  <your-browser-link>/api/health  and compare: a bare {\"ok\":true}"
  echo "     or a different boot.pid/host means the browser hits ANOTHER stack/pod"
  echo "     (possibly an old notebook session still alive) — fix the LINK, not this stack."
}

case "$CMD" in
  up)       up ;;
  down)     down ;;
  restart)  restart_one "${POS[0]:-}" ;;
  status)   status ;;
  doctor)   doctor ;;
  logs)     case "${POS[0]:-}" in
              api|web)  exec tail -n 40 -F "$LOG_ROOT/stdout/${2}/console.log" ;;
              build)    exec tail -n 40 -F "$LOG_ROOT/stdout/web/build.log" ;;
              backend)  exec tail -n 40 -F "$LOG_ROOT/handler/backend/backend.log" ;;
              workers)  exec tail -n 20 -F "$LOG_ROOT"/handler/backend/workers/*.log ;;
              tts)      exec tail -n 20 -F "$LOG_ROOT"/handler/sidecar/tts*.log ;;
              sglang)   exec tail -n 20 -F "$LOG_ROOT"/handler/sidecar/sglang_*.log ;;
              *) exec tail -n 20 -F "$LOG_ROOT/stdout/api/console.log" "$LOG_ROOT/stdout/web/console.log" "$LOG_ROOT/handler/backend/backend.log" ;;
            esac ;;
  attach)   exec tmux attach -t "$SES" ;;
  *)        sed -n '2,33p' "$0"; exit 2 ;;
esac
